# list format ["card_name", "card_suit", card_value, counting_value]
def deck():
    basic_deck = [["Two", "Clubs", 2, 1],
              ["Two", "Diamonds", 2, 1],
              ["Two", "Hearts", 2, 1],
              ["Two", "Spades", 2, 1],  
              ["Three", "Clubs", 3, 1],
              ["Three", "Diamonds", 3, 1],
              ["Three", "Hearts", 3, 1],
              ["Three", "Spades", 3, 1],
              ["Four", "Clubs", 4, 1],
              ["Four", "Diamonds", 4, 1],
              ["Four", "Hearts", 4, 1],
              ["Four", "Spades", 4, 1],
              ["Five", "Clubs", 5, 1],
              ["Five", "Diamonds", 5, 1],
              ["Five", "Hearts", 5, 1],
              ["Five", "Spades", 5, 1],
              ["Six", "Clubs", 6, 1],
              ["Six", "Diamonds", 6, 1],
              ["Six", "Hearts", 6, 1],
              ["Six", "Spades", 6, 1],
              ["Seven", "Clubs", 7, 0],
              ["Seven", "Diamonds", 7, 0],
              ["Seven", "Hearts", 7, 0],
              ["Seven", "Spades", 7, 0],
              ["Eight", "Clubs", 8, 0],
              ["Eight", "Diamonds", 8, 0],
              ["Eight", "Hearts", 8, 0],
              ["Eight", "Spades", 8, 0],
              ["Nine", "Clubs", 9, 0],
              ["Nine", "Diamonds", 9, 0],
              ["Nine", "Hearts", 9, 0],
              ["Nine", "Spades", 9, 0],
              ["Ten", "Clubs", 10, -1],
              ["Ten", "Diamonds", 10, -1],
              ["Ten", "Hearts", 10, -1],
              ["Ten", "Spades", 10, -1],
              ["Jack", "Clubs", 10, -1],
              ["Jack", "Diamonds", 10, -1],
              ["Jack", "Hearts", 10, -1],
              ["Jack", "Spades", 10, -1],
              ["Queen", "Clubs", 10, -1],
              ["Queen", "Diamonds", 10, -1],
              ["Queen", "Hearts", 10, -1],
              ["Queen", "Spades", 10, -1],
              ["King", "Clubs", 10, -1],
              ["King", "Diamonds", 10, -1],
              ["King", "Hearts", 10, -1],
              ["King", "Spades", 10, -1],
              ["Ace", "Clubs", 11, -1],
              ["Ace", "Diamonds", 11, -1],
              ["Ace", "Hearts", 11, -1],
              ["Ace", "Spades", 11, -1]
]
    return basic_deck
